name: Send Daily Logistics Newsletter

on:
  workflow_dispatch:
    inputs:
      job_to_run:
        description: '어떤 작업을 실행할까요? (daily/weekly)'
        required: true
        default: 'daily'
        type: choice
        options:
          - daily
          - weekly
  schedule:
    #  위클리/데일리 스케줄을 모두 KST 오전 8시로 통일
    # 1. 위클리: 한국 시간(KST)으로 매주 '월요일' 오전 8시에 실행 (UTC 기준 일요일 23:00)
    - cron: '0 23 * * 0'
    # 2. 데일리: 한국 시간(KST)으로 '화~일요일' 매일 아침 8시에 실행 (UTC 기준 월~토 23:00)
    - cron: '0 23 * * 1-6'

permissions:
  contents: write

jobs:
  # =======================================================
  # 위클리 뉴스레터 작업 (월요일 오전 8시 실행)
  # =======================================================
  weekly-job:
    # cron 스케줄이 일요일 23시(UTC)일 경우에만 이 작업이 실행
    if: github.event.schedule == '0 23 * * 0' || (github.event_name == 'workflow_dispatch' && github.event.inputs.job_to_run == 'weekly')

    runs-on: ubuntu-latest

    steps:
    - name: '소스 코드 가져오기 (Checkout)'
      uses: actions/checkout@v3

    - name: '파이썬 환경 설정'
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: '의존성 캐시'
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: '의존성 설치'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: '한글 폰트 설치 (나눔고딕)'
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-nanum
        
    - name: '[핵심] 실행 모드를 "weekly"로 변경'
      run: sed -i "s/EXECUTION_MODE = 'daily'/EXECUTION_MODE = 'weekly'/" config.py
      
    - name: '스크립트 실행 (위클리 모드)'
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        DAILY_RECIPIENT_LIST: ${{ secrets.DAILY_RECIPIENT_LIST }}
        WEEKLY_RECIPIENT_LIST: ${{ secrets.WEEKLY_RECIPIENT_LIST }}
        OPINET_API_KEY: ${{ secrets.OPINET_API_KEY }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python news_collector.py
      
    - name: '최신 변경사항 PULL'
      run: git pull

    - name: '변경된 파일 커밋 & 푸시'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update weekly newsletter history and archive"
        file_pattern: "sent_links_logistics.txt previous_*.json archive weekly_candidates.json"

  # =======================================================
  # 데일리 뉴스레터 작업 (화~일요일 오전 8시 실행)
  # =======================================================
  daily-job:
    # cron 스케줄이 월~토요일 23시(UTC)일 경우에만 이 작업이 실행됩니다.
    if: github.event.schedule == '0 23 * * 1-6' || (github.event_name == 'workflow_dispatch' && github.event.inputs.job_to_run == 'daily')
    runs-on: ubuntu-latest

    steps:
    - name: '소스 코드 가져오기 (Checkout)'
      uses: actions/checkout@v3

    - name: '파이썬 환경 설정'
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: '의존성 캐시'
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: '의존성 설치'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: '한글 폰트 설치 (나눔고딕)'
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-nanum

    - name: '스크립트 실행 (데일리 모드)'
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        DAILY_RECIPIENT_LIST: ${{ secrets.DAILY_RECIPIENT_LIST }}
        WEEKLY_RECIPIENT_LIST: ${{ secrets.WEEKLY_RECIPIENT_LIST }}
        OPINET_API_KEY: ${{ secrets.OPINET_API_KEY }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python news_collector.py
      
    - name: '최신 변경사항 PULL'
      run: git pull

    - name: '변경된 파일 커밋 & 푸시'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update daily newsletter history and archive"
        file_pattern: "sent_links_logistics.txt previous_*.json archive weekly_candidates.json"
