name: Send Daily Logistics Newsletter

on:
  schedule:
    # 한국 시간(KST)으로 매일 아침 8시에 실행 (UTC 기준 23시)
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # ✨ [수정] 불필요한 pip cache purge 명령어 제거
        pip install -r requirements.txt

    - name: Install Korean font (Nanum Gothic)
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-nanum
        sudo fc-cache -fv
        fc-list | grep -i "NanumGothic" || echo "NanumGothic 설치 확인 실패"

    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        RECIPIENT_LIST: ${{ secrets.RECIPIENT_LIST }}
        OPINET_API_KEY: ${{ secrets.OPINET_API_KEY }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python news_collector.py
    
    # ✨ [수정] 자동 커밋 전, 원격 저장소의 최신 변경사항을 먼저 받아와서 충돌을 방지합니다.
    - name: Pull latest changes
      run: git pull

    # ✨ [수정] 자동 커밋 로직을 git-auto-commit-action 하나로 통일합니다.
    - name: Commit and push updated files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update newsletter history and archive"
        # ✨ [수정] previous_*.json을 사용하여 존재하는 히스토리 파일만 커밋하도록 변경
        file_pattern: "sent_links_logistics.txt previous_*.json archive"
